#!/bin/bash

cd $(dirname "$0")

help() {
	echo "Usage: $0 version [project_dir]";
	exit -1
}

if [ -z $1 ]; then
	help
fi


list=(../pubspec.yaml ../snap/snapcraft.yaml);

for each in ${list[@]}; do
	echo "[!] Updating $each"
	sed -i "s/^version: \([0-9\.\+\-]*\)$/version: $1/" "$each"
	git add $each
done;

git commit -am "Updated version to $1"
git tag v$1 master
echo "Tagged release, please use: "
echo "$ git push origin v$1"
echo "to upload the Release."