#!/usr/bin/env python3

import ruamel.yaml
import os
import sys

files = ['../snap/snapcraft.yaml', '../pubspec.yaml']

def help():
  print(f"Usage: {sys.argv[0]} bugfix|minor|major")


# chdir to scripts directory if script is launched from somwhere elase
os.chdir(os.path.dirname(sys.argv[0]))

if len(sys.argv) > 1:
  change_part = sys.argv[1]
  
  doc = ruamel.yaml.load(file := open(files[0]), Loader=ruamel.yaml.RoundTripLoader)
  version = doc['version']
  version_code = None
  file.close()

  if '+' in version:
    slitted = version.split('+')
    version = slitted[0]
    version_code = int(slitted[1])
    version_code += 1
  else:
    version_code = 2

  x, y, z = map(int, version.split('.'))

  if change_part == "major":
    x += 1
    y = 0
    z = 0
  elif change_part == "minor":
    y += 1
    z = 0
  elif change_part == "bugfix":
    z += 1

  update_version = f"{x}.{y}.{z}"

  if version_code:
    update_version += f"+{version_code}"


  for each_file in files:
    output = None
    with open(each_file) as file:
      our_input = ruamel.yaml.load(file, Loader=ruamel.yaml.RoundTripLoader)
      our_input['version'] = update_version
      output = ruamel.yaml.dump(our_input, Dumper=ruamel.yaml.RoundTripDumper)

    if output:
      with open(each_file, "w") as file:
        file.write(output)

  commit = input(f"Commit? {update_version} [Y/n] ")
  if commit == "" or commit.lower() == "y":
    os.system(
        f"git add {' '.join(files)} && git commit -m 'Updated version to {update_version}'")
    print(f"[✅] Updated version to {update_version}")
    tag = input("Tag release? [Y/n] ")

    if tag == "" or tag.lower() == "y":
      tagName = f"v{update_version}"
      os.system(f"git tag {tagName}")
      print(f"Tagged release as {tagName}")
      push = input("Push Tag? [y/N] ")
      pushCommand = f"git push && git push origin {tagName}"
      if push.lower() == "y":
        os.system(pushCommand)
        print("Tag pushed")
      else: 
        print(f"Use this afterwards: $ {pushCommand}")

else:
  help()
