name: uet-lms
version: 0.1.2+11
summary: UET's LMS
description: UET's LMS Student Portal

confinement: devmode
base: core18
grade: devel

slots:
  dbus-svc: # name that is used with 'snap connect' on slots side
    interface: dbus
    bus: session
    name: org.freedesktop.DBus

apps:
  uet-lms:
    command: uet_lms
    extensions: [flutter-dev]
    slots: [dbus-svc]
    plugs:
      - network
      - mount-observe
      - x11
      - home
      - removable-media
      - browser-support
      - password-manager-service
    
parts:
  uet-lms:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart 
    build-packages:
     - libsecret-1-dev
     - libjsoncpp-dev
    stage-packages:
     - libsecret-1-dev
     - libjsoncpp1-dev


