#!/bin/bash

cd $(dirname "$0")

help() {
	echo "Usage: $0 version [project_dir]";
	exit -1
}

if [ -z $1 ]; then
	help
fi


list=(../pubspec.yaml ../snap/snapcraft.yaml);

for each in ${list[@]}; do
	echo "[!] Updating $each"
	sed -i "s/^version: \([0-9\.\+\-]*\)$/version: $1/" "$each"
done;
