name: uet-lms
version: 0.1.0
summary: UET's LMS
description: UET's LMS Student Portal

confinement: strict
base: core18
grade: devel

apps:
  uet-lms:
    command: uet_lms
    extensions: [flutter-dev]
    plugs:
      - network
      - mount-observe
      - x11
      - home

parts:
  uet-lms:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart 
    stage-packages:
     - libsecret-1-dev
     - libjsoncpp-dev


