name: Snap Build

on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - run: |
        echo ${{secrets.SNAPCRAFT_TOKEN}} | snapcraft login --with -
        snapcraft upload ${{steps.snapcraft.outputs.snap}}
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{steps.snapcraft.outputs.snap}}
