name: Snap Build

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: install multipass
        run: snap install multipass
      # You can now run Snapcraft shell commands
      - name: Use Snapcraft
        run: snapcraft


      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test.snap
          path: ./*.snap
